accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('logout/', views.logoutView, name='logout'),
]

land_aquisition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('property/', include('property.urls')),
]

property/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.homeView, name='home'),
    path('update_property/<int:pk>/', views.updatePropertyView, name='update_property'),
    path('property_detail/<int:pk>/', views.propertyDetailView, name='property_detail'),
    path('delete_property/<int:pk>/', views.deletePropertyView, name='delete_property'),
    path('update_property_status/<int:pk>/', views.updatePropertyStatusView, name='update_property_status'),

    path('update_comment/<int:pk>/', views.updateComment, name='update_comment'),
    path('delete_comment/<int:comment_pk>/<int:property_pk>/', views.deleteCommentView, name='delete_comment'),
    path('fetch_notifications/', views.fetch_notifications, name='fetch_notifications'),
    path('mark_notification_read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('view_notification_detail/<int:notification_pk>/<int:property_pk>/', views.viewNotificationDetail, name='view_notification_detail'),

    path('confirm_meeting/<int:meeting_id>/', views.confirmMeeting, name='confirm_meeting'),
    path('details/<int:meeting_id>/', views.meetingDetails, name='meeting_details'),
    path('calendar/<int:property_pk>/', views.calendarView, name='calendar'),
    path('available_time_slots/', views.availableTimeSlots, name='available_time_slots'),
    path('book_meeting/', views.bookMeeting, name='book_meeting'),
    path('meetings/<int:user_pk>/', views.fetchAllMeetings, name='meetings'),
    path('attend_meeting/<int:meeting_id>/', views.attendMeeting, name='attend_meeting'),
]

property/models.py
from django.db import models
from django.contrib.auth.models import User

class PropertyListing(models.Model):
    STATUS_CHOICES = (
        ('APPROVED', 'approved'),
        ('PENDING', 'pending'),
        ('UNDER DISCUSSION', 'under discussion'),
        ('REJECTED', 'REJECT'),
    )

    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    area = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    
    property_type = models.CharField(max_length=100, blank=True, null=True)
    listing_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='PENDING')
    address = models.CharField(max_length=255, null=True, blank=True, default="X-Y-Z")
    is_active = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

class PropertyComment(models.Model):
    comment = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    property = models.ForeignKey(PropertyListing, on_delete=models.DO_NOTHING, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment
    
class Meeting(models.Model):
    admin = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='admin_meetings')
    landowner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='landowner_meetings')
    date = models.DateField(null=True, blank=True)
    time = models.TimeField(null=True, blank=True)
    confirmed = models.BooleanField(default=False)
    attended = models.BooleanField(default=False)

    def __str__(self):
        return f"Meeting on {self.date} at {self.time} with {self.landowner}"
    
class Notification(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    detail = models.TextField(null=True, blank=True)
    property = models.ForeignKey(PropertyListing, on_delete=models.DO_NOTHING, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    comment = models.ForeignKey(PropertyComment, on_delete=models.DO_NOTHING, blank=True, null=True)
    meeting = models.ForeignKey(Meeting, on_delete=models.DO_NOTHING, blank=True, null=True)
    is_readed = models.BooleanField(default=False)
    notification_type = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

property/forms.py
from django import forms
from .models import PropertyListing, Meeting

class PropertyListingForm(forms.ModelForm):
    title = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Property Title'})
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Property Description'})
    )
    area = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Property Area'})
    )
    price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Property Price'})
    )
    property_type = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Property Type'})
    )
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'location-input', 'placeholder': 'Click to select location'})
    )

    class Meta:
        model = PropertyListing
        fields = [
            'title', 
            'description', 
            'location', 
            'area', 
            'price', 
            'property_type',
        ]

    def save(self, commit=True, owner=None):
        listing = super(PropertyListingForm, self).save(commit=False)
        if owner:
            listing.owner = owner
        if commit:
            listing.save()
        return listing
    
    def delete(self, commit=True):
        listing = super(PropertyListingForm, self).save(commit=False)
        if commit:
            listing.is_active = False
            listing.save()
        return listing
    
class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ['landowner', 'date', 'time']
        widgets = {
            'date': forms.SelectDateWidget(),
            'time': forms.TimeInput(format='%H:%M'),
        }

property/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import PropertyListing, PropertyComment, Notification, Meeting
from .forms import PropertyListingForm, MeetingForm
from django.contrib import messages
from django.http import JsonResponse
from django.utils import timezone
from datetime import timedelta, datetime
from property.utils.createNotification import create_notification
from property.utils.getNotifications import get_notifications_for_user
import json
from .decorators import allowed_users

@login_required
# @allowed_users(allowed_roles=['admin'])
def homeView(request):
    try:
        group = request.user.groups.all()[0].name

        if group == 'customer':
            form = PropertyListingForm()
            user_property = PropertyListing.objects.filter(is_active=True).order_by('-id')

            context = {
                'properties': user_property,
                'form': form
            }

            if request.method == 'POST':
                form = PropertyListingForm(request.POST)
                print("form valid => ", form)
                if form.is_valid():
                    property = form.save(commit=False)
                    property.owner = request.user
                    property.save()

                    create_notification(
                        title="New Property Added",
                        detail=f"A new property was added by {request.user.username}: {request.POST['title']}",
                        property=property,
                        user=request.user,
                        notification_type='property'
                    )

                    return redirect('home')

            return render(request, 'property/home.html', context)
        elif group == 'admin':
            properties = PropertyListing.objects.filter(is_active=True).order_by('-id')

            context = {
                'properties': properties,
            }

            return render(request, 'property/admin/home.html', context)
        else:
            return redirect('login')
    except Exception as e:
        print("error => ",e)
        messages.success(request, 'Your profile is not complete for login')
        return redirect('logout')

@login_required
def updatePropertyView(request, pk):
    try:
        property = PropertyListing.objects.get(pk=pk, is_active=True)
    except Exception as e:
        pass
    form = PropertyListingForm(instance=property)

    if request.method == 'POST':
        form = PropertyListingForm(request.POST, instance=property)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form}
    return render(request, 'property/updateProperty.html', context)

@login_required
def deletePropertyView(request, pk):
    try:
        property = PropertyListing.objects.get(pk=pk, is_active=True)
        property.is_active = False

        property.save()
        return redirect('home')
    except Exception as e:
        pass

@login_required
def propertyDetailView(request, pk):
    try:
        property = PropertyListing.objects.get(pk=pk, is_active=True)
        comments = PropertyComment.objects.filter(property=property).order_by('-created_at')
    except Exception as e:
        pass

    if request.method == 'POST':
        new_comment = PropertyComment(
            comment=request.POST['comment'],
            user=request.user,
            property=property
        )
        new_comment.save()

        # Create a notification for the new comment
        create_notification(
            title="New Comment Added",
            detail=f"A new comment was added by {request.user.username}: {request.POST['comment']}",
            property=property,
            user=request.user,
            comment=new_comment,
            notification_type='comment'
        )

    context = {'property': property, 'comments': comments}
    return render(request, 'property/detailView.html', context)

@login_required
def updateComment(request, pk):
    try:
        data = json.loads(request.body)
        comment_text = data.get('comment')

        comment = PropertyComment.objects.get(pk=pk)
        if comment:
            comment.comment = comment_text
            comment.save()
            return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'success': False})

@login_required
def deleteCommentView(request, comment_pk, property_pk):
    try:
        comment = PropertyComment.objects.get(pk=comment_pk)
        
        if comment:
            comment.delete()
        
        return redirect('property_detail', pk=property_pk)
    except Exception as e:
        pass

@login_required
def updatePropertyStatusView(request, pk):
    try:
        property = PropertyListing.objects.get(pk=pk, is_active=True)
    except Exception as e:
        pass

    if request.method == 'POST':
        property.status = request.POST['status']
        property.save()

        create_notification(
            title="Property status has been updated",
            detail=f"{request.user.username}: has updated the status of your property",
            property=property,
            user=request.user,
            notification_type='status'
        )

    return redirect('property_detail', pk=pk)


@login_required
def fetch_notifications(request):
    if request.user.is_authenticated:
        group = request.user.groups.all()[0].name
        
        if group == 'admin':
            user_properties = PropertyListing.objects.filter(is_active=True).order_by('-id')
        else:
            user_properties = PropertyListing.objects.filter(owner=request.user, is_active=True).order_by('-id')
        
        notifications = get_notifications_for_user(
            user=request.user,
            property_filter=user_properties,
            notification_types=['comment', 'status', 'meeting'] if group == 'customer' else ['comment', 'property']
        )

        notifications_data = [
            {
                'id': notification.pk,
                'title': notification.title,
                'detail': notification.detail,
                'property': notification.property.pk if notification.property else None,
                'meeting': notification.meeting.pk if notification.meeting else None,
                'type': notification.notification_type,
                'created_at': notification.created_at.strftime('%Y-%m-%d %H:%M:%S')
            }
            for notification in notifications
        ]
        return JsonResponse({'notifications': notifications_data})
    else:
        return JsonResponse({'notifications': []})


@login_required
def mark_notification_read(request, notification_id):
    if request.method == 'POST' and request.user.is_authenticated:
        print('getting post.....')
        try:
            notification = Notification.objects.get(id=notification_id)
            notification.is_readed = True
            notification.save()
            return JsonResponse({'success': True})
        except Notification.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Notification does not exist'})
    return JsonResponse({'success': False, 'error': 'Invalid request'})

@login_required
def viewNotificationDetail(request, notification_pk, property_pk):
    if request.method == 'GET' and request.user.is_authenticated:

        try:
            notification = Notification.objects.get(pk=notification_pk)

            if notification:
                notification.is_readed = True
                notification.save()
                return JsonResponse({'success': True, 'propertyId': property_pk})
        except Exception as e:
            pass

        return JsonResponse({'success': False, 'error': 'Invalid request'})

@login_required
def confirmMeeting(request, meeting_id):
    meeting = Meeting.objects.get(id=meeting_id)
    if request.method == 'POST':
        meeting.confirmed = True
        meeting.save()
        return redirect('meetings', request.user.id)
    return render(request, 'property/admin/confirm_meeting.html', {'meeting': meeting})

@login_required
def meetingDetails(request, meeting_id):
    meeting = Meeting.objects.get(id=meeting_id)
    return render(request, 'property/admin/meeting_details.html', {'meeting': meeting})

@login_required
def calendarView(request, property_pk):
    property = None
    try:
        property = PropertyListing.objects.get(pk=property_pk, is_active=True)
    except Exception as e:
        pass

    context = {'property': property}
    return render(request, 'property/admin/calendar_view.html', context)

@login_required
def availableTimeSlots(request):
    today = timezone.now().date()
    time_slots = []
    booked_slots = Meeting.objects.filter(date__gte=today)
    
    for i in range(30):
        date = today + timedelta(days=i)
        for hour in range(9, 17):
            start_time = datetime.combine(date, datetime.min.time()) + timedelta(hours=hour)
            end_time = start_time + timedelta(hours=1)
            slot_info = {
                'start': start_time.isoformat(),
                'end': end_time.isoformat(),
                'title': f'{hour}:00-{hour+1}:00',
                'display': 'block'
            }
            # Check if the slot is booked
            if booked_slots.filter(date=date, time__hour=hour).exists():
                slot_info['backgroundColor'] = 'red'
                slot_info['clickable'] = False
                slot_info['title'] = slot_info['title']+' Reserved'
            time_slots.append(slot_info)
    return JsonResponse(time_slots, safe=False)


@csrf_exempt
@login_required
def bookMeeting(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        date = data['date']
        time = data['time']

property/templates/property/addPropertyModal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Property</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        <label for="id_area">Area</label>
                        {{ form.area }}
                    </div>
                    <div class="form-group">
                        <label for="id_price">Price</label>
                        {{ form.price }}
                    </div>
                    <div class="form-group">
                        <label for="id_property_type">Property Type</label>
                        {{ form.property_type }}
                    </div>
                    <div class="form-group">
                        <label for="id_location">Location</label>
                        <input type="text" id="location-input" name="location" class="form-control" placeholder="Click to select location">
                        <button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#mapModal">Select Location</button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Map Modal -->
<div class="modal fade" id="mapModal" aria-labelledby="mapModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mapModalLabel">Select Location</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="pac-input" class="form-control mb-3" type="text" placeholder="Search Box">
                <div id="map"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save-location">Save Location</button>
            </div>
        </div>
    </div>
</div>

property/templates/property/detailView.html
{% extends "property/main.html" %}
{% load custom_filters %}

{% block content %}
    <div class="container mt-5">
        <div class="alert alert-primary d-flex justify-content-between" role="alert">
            <span class="align-self-center">Home / Property / <span style="color: gray;">Details</span></span>
            {% if request.user|has_group:'admin' %}
                <a href="{% url 'calendar' property.id %}" class="btn btn-sm btn-primary">Schedule a Meeting</a>
            {% endif %}
        </div>

        <div class="property-details-holder">
            <div class="card mb-3">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5>{{property.title}}</h5>

                    {% if request.user|has_group:'admin' %}
                        <div class="row">
                            <div class="col-sm-12">
                                <form method="POST" action="{% url 'update_property_status' property.id %}" class="inline-form">
                                    {% csrf_token %}
                                    <select name="status" id="cars" class="form-control">
                                        {% if property.status %}
                                            <option value="{{property.status}}">{{property.status}}</option>
                                        {% endif %}
                                        <option value="APPROVED">APPROVED</option>
                                        <option value="PENDING">PENDING</option>
                                        <option value="UNDER DISCUSSION">UNDER DISCUSSION</option>
                                        <option value="REJECTED">REJECT</option>
                                    </select>
                                    <button class="btn btn-primary" type="submit">Update</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-around">
                        <h5 class="card-title"> Location: {{property.location}}</h5>
                        <h5 class="card-title">Address: {{property.address}}</h5>
                    </div>

                    <div class="mt-3">
                        <span class="label">Description: </span> <br>
                        <p class="card-text">{{property.description}}</p>
                    </div>

                    <div class="d-flex justify-content-around mt-5">
                        <div>
                            <span class="label">Area: </span> <br>
                            <span class="value">{{property.area}} f</span>
                        </div>

                        <div>
                            <span class="label">Price: </span> <br>
                            <span class="value">{{property.price}} PKR</span>
                        </div>

                        <div>
                            <span class="label">Status: </span> <br>
                            <span class="value">{{property.status}}</span>
                        </div>

                        <div>
                            <span class="label">Date: </span> <br>
                            <span class="value">{{property.listing_date}}</span>
                        </div>
                    </div>
                </div>
            </div>

            <span class="label mb-3">Comments</span><br>

            {% for comment in comments %}
                <div class="comment-wrapper" id="comment-wrapper-{{ comment.id }}">
                    <div class="d-flex justify-content-between">
                        <span class="name-container">{{ comment.user }}</span>
                        {% if request.user == comment.user %}
                            <div class="comment-btn-holder">
                                <a href="javascript:void(0);" onclick="editComment({{ comment.id }})">Edit</a>
                                <a href="{% url 'delete_comment' comment.id property.id %}">Delete</a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="card text-bg-light comment-container mb-3" id="comment-{{ comment.id }}">
                        {{ comment.comment }}
                    </div>
                    <div class="card text-bg-light comment-edit-container mb-3 d-none" id="edit-comment-{{ comment.id }}">
                        <textarea class="edit-comment-box" id="edit-comment-text-{{ comment.id }}" rows="3">{{ comment.comment }}</textarea>
                        <button class="btn btn-sm btn-primary" onclick="saveComment({{ comment.id }})">Save</button>
                    </div>
                </div>
            {% endfor %}

            
        </div>

        <div 
            class="card text-bg-light mt-3 text-holder"
        >
            <form method="POST" action="" style="width: 100%;">
                {% csrf_token %}
                <input type="text" name="comment" placeholder="Write you comment" class="comment-box" />
                <button type="submit" class="btn-icon-holder float-end"><i class="bi bi-send-fill send-btn"></i></button>  
            </form>
        </div>
    </div>

{% endblock content %}

property/templates/property/home.html
{% extends "property/main.html" %}

{% block content %}
    <div class="container mt-5">
        <div class="alert alert-primary d-flex justify-content-between" role="alert">
            <span class="align-self-center">Home / <span style="color: gray;">Property</span></span>
            <button type="button" class="btn btn-sm btn-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add New +
            </button>
        </div>

        <div class="row">
            {% for property in properties %}
                <div class="col-lg-3 col-md-3 col-sm-6 d-flex justify-content-center">
                    <div class="card text-bg-light mb-3 shadow" style="width: 30rem;">
                        <div class="card-header d-flex justify-content-between">
                            <span>
                                {{ property.title|title|slice:":22" }}{% if property.title|length > 22 %}...{% endif %}
                            </span>
                            {% if request.user == property.owner %}
                                <div>
                                    <a href="{% url 'update_property' property.id %}" class="remove-underline">
                                        <i 
                                            class="bi bi-pen-fill" 
                                            style="color: blue; margin-right: 10px;"
                                        ></i>
                                    </a>
                                    <a class="remove-underline">
                                        <i 
                                            class="bi bi-archive-fill pointer delete-property-icon" style="color: red;"
                                            data-bs-toggle="modal" data-bs-target="#warningAlert"
                                            data-property-id="{{ property.id }}"
                                        ></i>
                                    </a>
                                </div>                            
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                {{ property.description|slice:":100" }}{% if property.description|length > 100 %}...{% endif %}
                            </p>

                            <div class="d-flex justify-content-between">
                                <div>
                                    <span class="label">Area: </span> <br>
                                    <span class="value">{{property.area}} f</span>
                                </div>

                                <div style="width: 100px;">
                                    <span class="label">Price: </span> <br>
                                    <span class="value">{{property.price}} PKR</span>
                                </div>
                            </div>

                            <div class="d-flex justify-content-between mt-2">
                                <div>
                                    <span class="label">Status: </span> <br>
                                    <span class="value">{{property.status}}</span>
                                </div>
                                <div>
                                    <span class="label">Date: </span> <br>
                                    <span class="value">{{property.listing_date}}</span>
                                </div>
                            </div>
                            <a href="{% url 'property_detail' property.id %}" class="float-end mt-3">Show more...</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

property/templates/property/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>Land Aquisition</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.10.1/main.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
  </head>
  <body>
    {% include "property/navbar.html" %}
    {% include "property/notificationSidebar.html" %}
    {% include "property/addPropertyModal.html" %}
    {% include "property/warningAlert.html" %}

    {% block content %}
        
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8blv0O6kxNClLd_pzpsknVuiShUPKE0U&libraries=places&callback=initMap"></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.13/index.global.min.js'></script>
    <script src="{% static '/js/script.js' %}"></script>
    <script src="{% static '/js/calendar.js' %}"></script>
    <script src="{% static '/js/videoChat.js' %}"></script>
  </body>
</html>